# Generated by Django 4.2 on 2023-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('student_id', models.CharField(max_length=10)),
                ('stud_class', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('teacher_id', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
